#!/bin/bash
echo "Set DB_USER"
DB_USER=seb
echo "Set DB_PASSWORD"
DB_PASSWORD=seb
echo "Set USER_LEVEL"
USER_LEVEL=3
echo "Set SYSTEM_LEVEL"
SYSTEM_LEVEL=2
echo "Set THERMOSTAT_LEVEL"
THERMOSTAT_LEVEL=1
